### PR TITLE
Job profiler

### PR DESCRIPTION
**Pull request by EugeneKostrikov**

### CODE REVIEW

**Comment by EugeneKostrikov** [comment]
Sorry, selected wrong target repo.. Feel free to merge though.

**Comment by lahirs2** [comment]
Hi Eugene,

Couple of questions on the pull request
1. Could you explain this feature "Allow to configure worker run parallel jobs". I was looking for something similar and it seems its already solved.
2. When do you think this PR can be approved?

- SID

**Comment by EugeneKostrikov** [comment]
Hey Sid,

Running parallel job literarily kicks off new jobs as they get enqueued and doesn't wait for previous job to complete. The drawback atm is that you cannot set any limit on the number of jobs running in parallel. 

Can be approved any time - we use that in production environment quite a while, so it's stable enough. 

Eugene

**Comment by scttnlsn** [comment]
What is the use case behind the `parallel` option?  Won't this cause the workers to keep dequeueing jobs as fast as they can and consume memory with no bounds?

I'm also wondering if the profiling could be accomplished by listening to worker events (as opposed to being inside the Monq core).  Curious if you tried this at all?

**Comment by EugeneKostrikov** [comment]
The use case is to be able to kick jobs off as soon as they arrive no matter what's currently running. It has no bounds indeed and need to be conscious what's the jobs throughput and how much resources it could consume. Basically that's why we are not raising full PR yet as it's unlikely to meet everyones expectation.

As to profiling - the idea is to be able to inject profiler into the worker handler so that it can log milestones as it progresses through the job. Not sure if event-based approach would fit here at all.

**Comment by scttnlsn** [comment]
OK, thanks.  I don't think I'll merge this.  I'd be happy to reconsider if you feel strongly that either of these features should be in the core.  I'd also consider adding additional worker events if there's something currently preventing the profiler from being hooked up via the emitted events.

**Comment by lahirs2** [comment]
At the moment, I am trying to build a functionality "Work Queues" provided by RabbitMQ (https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html). The idea is to give ability scale the number of tasks performed at a time, keeping the paradigm of queue in place. I am not sure if this functionality should be part of monq or it should be built on top of it.

**Pull request closed without merging**
