### PR TITLE
Create worker queue with options

### PR DESCRIPTION
**Pull request by dsanel**
This will allow user to change collection name while creating worker
```
var worker = client.worker(['example'], { collection: 'workersCollectionName'});
```

### CODE REVIEW

**Comment by scttnlsn** [comment]
@dsanel What if the worker is operating on multiple queues.  You'd be passing the same options into each queue constructor.

**Comment by dsanel** [comment]
@scttnlsn With this code, every queue in the array will have the same options (collection name). Of course, if we want to create multiple "groups" of queues, we will need to create multiple workers for each group.

Another solution can be to extend the first parameter of function worker to accept array of objects. Here is a simple example:
```
var worker = client.worker([
   {queue: 'example1', options: {collection: 'jobs_test1'}},
   {queue: 'example2', options: {collection: 'jobs_test2'}},
   {queue: 'example3'},  
   {queue: 'example4'}, 
   {queue: 'example5'}
]);
```

**Comment by scttnlsn** [comment]
This seems a little extraneous to me.  I think the following is a little simpler:

```js
var worker = client.worker([
  client.queue('example1', { collection: 'jobs_test1' }),
  client.queue('exampel2', { collection: 'jobs_test2' }),
  ...
]);
```

Please re-open if that does not satisfy your use case.

**Comment by dsanel** [comment]
You're totally right, I overlooked this solution. :blush:

https://github.com/scttnlsn/monq/blob/master/lib/connection.js#L20

Thanks for help!

**Comment by scttnlsn** [comment]
Glad it'll work!  No problem.

**Pull request closed without merging**
